version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: sensgrid_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: sensgrid
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - sensgrid_network

  # Backend API for the Admin
  backend:
    build:
      context: ./Admin/backend
      dockerfile: Dockerfile
    container_name: sensgrid_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb+srv://admin:admin123@cluster0.kplpa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      JWT_SECRET: 1844fa85291aa39cec4de0ef4dbfd934e51ac0689bde910ac3a8212bf8a8be6367c733bbf49ff842165b891716bf78254b10dddefea27a3e76829da6489bc6ae
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./Admin/backend:/app
      - /app/node_modules
    networks:
      - sensgrid_network

  # Frontend for the Admin
  frontend:
    build:
      context: ./Admin/frontend
      dockerfile: Dockerfile
    container_name: sensgrid_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "8081:8081"
    depends_on:
      - backend
    volumes:
      - ./Admin/frontend:/app
      - /app/node_modules
    networks:
      - sensgrid_network

# ==============================================
# This Section is for the Web Application 

  frontend1:
    build:
      context: ./Web/frontend
      dockerfile: Dockerfile
    container_name: sensgrid_web_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Web/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5001/api
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - backend1
    networks:
      - sensgrid_network

  backend1:
    build:
      context: ./Web/backend
      dockerfile: Dockerfile
    container_name: sensgrid_web_backend
    ports:
      - "5001:5001"
    volumes:
      - ./Web/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/sensgrid?authSource=admin
      - JWT_SECRET=1844fa85291aa39cec4de0ef4dbfd934e51ac0689bde910ac3a8212bf8a8be6367c733bbf49ff842165b891716bf78254b10dddefea27a3e76829da6489bc6ae
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
    networks:
      - sensgrid_network

volumes:
  mongodb_data:
    driver: local

networks:
  sensgrid_network:
    driver: bridge
